Table employee {
  id int [pk, increment]
  name varchar(255) [not null]
  roles varchar(255) [not null]
  login varchar(255) [not null]
  password varchar(255) [not null]
  salt varchar(255) [not null]
  deleted boolean [not null]
}

Table document_upload {
  id int [pk, increment]
  customer_id int [not null, ref: > customer.id]
  filename varchar(255) [not null]
}

Table customer {
  id int [pk, increment]
  name varchar(255)
  phone_number varchar(255) [not null]
  selfie_filename varchar(255)
  profile_confirmed bool [not null, default: false]
  banned_until date
}

Table document {
  id int [pk, increment]
  customer_id int [ref: > customer.id]
  first_name varchar(255) [not null]
  last_name varchar(255) [not null]
  birthdate date [not null]
  issued_on date [not null]
  valid_by date [not null]
  driving_exp_since date [not null]
  photo_filename varchar(255)
}

Table car {
  id int [pk, increment]
  model varchar(255) [not null]
  vin varchar(255) [not null]
  latitude double
  longitude double
  is_used bool [not null, default: false]
  is_visible bool [not null, default: true]
  comment varchar(255)
}

Table car_photos {
  id int [pk, increment]
  car_id int [not null, ref: > car.id]
  photo_filename varchar(255)
}

Table log {
  id int [pk, increment]
  type varchar(255) [not null]
  customer_id int [not null, ref: > customer.id]
  car_id int [not null, ref: > car.id]
  value varchar(255)
}
